# Generated by Django 5.2.8 on 2026-01-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
    ]
